# coding: utf-8

"""
    PatentDB 2.0

    API specification for PatentDB 2.0  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_by_patent_type_get(self):
        """Test case for find_by_patent_type_get

        Returns patent information for a given patent grant, application, or publication.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
