# coding: utf-8

# flake8: noqa
"""
    PatentDB 2.0

    API specification for PatentDB 2.0  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.inline_response200 import InlineResponse200
