# coding: utf-8

"""
    PatentDB 2.0

    API specification for PatentDB 2.0  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def find_by_patent_type_get(self, patent_type, number, **kwargs):  # noqa: E501
        """Returns patent information for a given patent grant, application, or publication.  # noqa: E501

        Eg. GET /find_by_grant?number=7654321 or GET /find_by_publication?number=20080156487  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.find_by_patent_type_get(patent_type, number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str patent_type: (required)
        :param str number: (required)
        :param bool include_description:
        :param bool include_claims:
        :return: InlineResponse200
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.find_by_patent_type_get_with_http_info(patent_type, number, **kwargs)  # noqa: E501
        else:
            (data) = self.find_by_patent_type_get_with_http_info(patent_type, number, **kwargs)  # noqa: E501
            return data

    def find_by_patent_type_get_with_http_info(self, patent_type, number, **kwargs):  # noqa: E501
        """Returns patent information for a given patent grant, application, or publication.  # noqa: E501

        Eg. GET /find_by_grant?number=7654321 or GET /find_by_publication?number=20080156487  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.find_by_patent_type_get_with_http_info(patent_type, number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str patent_type: (required)
        :param str number: (required)
        :param bool include_description:
        :param bool include_claims:
        :return: InlineResponse200
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['patent_type', 'number', 'include_description', 'include_claims']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method find_by_patent_type_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'patent_type' is set
        if ('patent_type' not in params or
                params['patent_type'] is None):
            raise ValueError("Missing the required parameter `patent_type` when calling `find_by_patent_type_get`")  # noqa: E501
        # verify the required parameter 'number' is set
        if ('number' not in params or
                params['number'] is None):
            raise ValueError("Missing the required parameter `number` when calling `find_by_patent_type_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'patent_type' in params:
            path_params['patent_type'] = params['patent_type']  # noqa: E501

        query_params = []
        if 'number' in params:
            query_params.append(('number', params['number']))  # noqa: E501
        if 'include_description' in params:
            query_params.append(('include_description', params['include_description']))  # noqa: E501
        if 'include_claims' in params:
            query_params.append(('include_claims', params['include_claims']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/find_by_{patent_type}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse200',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
